### ISSUE TITLE
Hardcoded url in about box (to register your project)

### ISSUE THREAD

**Issue by adulau** [cedricbonhomme/Freshermeat#9]
I found an hardcoded url in the about box:

https://github.com/cedricbonhomme/Freshermeat/blob/d145e5cf8fba934d549b6a0b7d9a217350c4cf93/src/web/templates/about.html#L26

**Comment by cedricbonhomme** [comment]
Lol. Thanks for the finding! I'll fix it. Never really tested this on the production instance, since it can not work with projects hosted on GitHub.

Fyi, I am currently adding endpoints to get more stats (aba37facd06ba85171fe641fcc7eaf52ac07f529).
I'll also add stats about forges (GitHub, GitLab, etc.) used to host projects.

**Comment by adulau** [comment]
Really cool! Thanks.

Another option, can we pivot per user who submitted project?

**Comment by cedricbonhomme** [comment]
Yes, good idea for the submitters !
